server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:li671207/cloud-config.git
          search-paths:
            - cloud-config
          default-label: master
  rabbitmq:
    host: 192.168.1.100
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

